### ISSUE TITLE
(Kenneth - Sprint 3) Develop communication with RabbitMQ server to publish messages

### ISSUE THREAD

**Issue by kejo1166** [cu-ecen-aeld/final-project-emma-harper#9]
DoD:

- [x] All RabbitMQ packages and dependencies are baked into image and working
- [x] RabbitMQ class is created
- [x] RabbitMQ class connection credentials are load from json file
- [x] RabbitMQ class allows connect/disconnect to server
- [x] RabbitMQ class handles unexpected sockets errors
- [x] RabbitMQ class published messages to server

Blockers:
None at this time

**Comment by kejo1166** [comment]
Was able to get pika baked in to image as an external package. This library is need to publish message to a rabbitmq server. [9b6f7c3](https://github.com/cu-ecen-aeld/final-project-kejo1166/commit/9b6f7c37c51772a5e3b85a7fec8d8c815036afc0)

![image](https://user-images.githubusercontent.com/86031233/162594720-7f1dfa4c-cf14-4cae-b522-95799cdf736b.png)

**Comment by kejo1166** [comment]
Ran into issue with missing the ssl library.  Pika requires SSL library to make a connection the rabbitmq server.  I exhausted manny SSL options in build root with no avail.

```
# cd /opt/aesd-sensehatlive/
# 
# python sensehatlive.py -v
Traceback (most recent call last):
  File "/opt/aesd-sensehatlive/sensehatlive.py", line 32, in <module>
    from sensehatlive.sensemanager.manager import SenseHatManager
  File "/opt/aesd-sensehatlive/sensehatlive/sensemanager/manager.py", line 30, in <module>
    from sensehatlive.messagebroker.rabbitmq import RabbitMQProducer
  File "/opt/aesd-sensehatlive/sensehatlive/messagebroker/rabbitmq.py", line 25, in <module>
    import pika
  File "/usr/lib/python3.9/site-packages/pika/__init__.py", line 10, in <module>
    
  File "/usr/lib/python3.9/site-packages/pika/connection.py", line 13, in <module>
  File "/usr/lib/python3.9/ssl.py", line 98, in <module>
ModuleNotFoundError: No module named '_ssl'
```

According to this [post](https://stackoverflow.com/questions/5128845/importerror-no-module-named-ssl) it appears python needs to be compiled with an SSL option.  I could not figure how to get builtroot to compile the library.  Also unable to download the recommended apt packages.  I was able to get the issue resolved by extracting the complied library from another raspberry pi and including the ssl library, dynamically, in my repo lib folder. [7fad4dc3](https://github.com/cu-ecen-aeld/final-project-kejo1166/commit/7fad4dc3a5f4add5083f5afd61ca6d319223319e)

![image](https://user-images.githubusercontent.com/86031233/162595131-2c326931-f977-45a0-8913-ef86ae5473ba.png)

**Comment by kejo1166** [comment]
Complete development of the rabbitmq class. [134847f](https://github.com/cu-ecen-aeld/final-project-kejo1166/commit/134847f9cd1065f52518e27870c9a2a87d1a442f)

![image](https://user-images.githubusercontent.com/86031233/162595183-8d2d0693-f479-4c58-b7b9-b755d055627f.png)

Able to publish messages to rabbitmq server.
![image](https://user-images.githubusercontent.com/86031233/162595199-fdfe175b-acb3-425b-9197-43ab5d06295e.png)

![image](https://user-images.githubusercontent.com/86031233/162595220-c222b574-ce4f-41ba-ab0f-3cac02fdf2fd.png)

**Comment by kejo1166** [comment]
Unexpected disconnection and reconnection are being handled. [be3ceed](https://github.com/cu-ecen-aeld/final-project-kejo1166/commit/be3ceed1a64a58c3f5cd364e1ba6c366aaa16426)

![image](https://user-images.githubusercontent.com/86031233/162596463-5f0b26d5-5814-46e8-bbb8-38863a22e71f.png)
